// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.feng.custom.info;

public final class Person {
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Profile_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Profile_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Profile_AddressEntry_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Profile_AddressEntry_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\014person.proto\032\031google/protobuf/any.prot" +
                        "o\"\221\002\n\007Profile\022\014\n\004name\030\001 \001(\t\022\031\n\003sex\030\002 \001(\016" +
                        "2\014.Profile.Sex\022\013\n\003age\030\003 \001(\005\022%\n\007details\030\004" +
                        " \001(\0132\024.google.protobuf.Any\022&\n\007address\030\005 " +
                        "\003(\0132\025.Profile.AddressEntry\022\023\n\tfather_no\030" +
                        "\006 \001(\tH\000\022\023\n\tmother_no\030\007 \001(\tH\000\032.\n\014AddressE" +
                        "ntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\030\n\003" +
                        "Sex\022\007\n\003BOY\020\000\022\010\n\004GIRL\020\001B\r\n\013family_infoB \n" +
                        "\024com.feng.custom.infoB\006PersonP\001b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                com.google.protobuf.AnyProto.getDescriptor(),
                        });
        internal_static_Profile_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_Profile_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Profile_descriptor,
                new java.lang.String[]{"Name", "Sex", "Age", "Details", "Address", "FatherNo", "MotherNo", "FamilyInfo",});
        internal_static_Profile_AddressEntry_descriptor =
                internal_static_Profile_descriptor.getNestedTypes().get(0);
        internal_static_Profile_AddressEntry_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Profile_AddressEntry_descriptor,
                new java.lang.String[]{"Key", "Value",});
        com.google.protobuf.AnyProto.getDescriptor();
    }
    private Person() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    // @@protoc_insertion_point(outer_class_scope)
}
