// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.feng.custom.info;

public interface ProfileOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Profile)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     *
     * @return The name.
     */
    java.lang.String getName();

    /**
     * <code>string name = 1;</code>
     *
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
    getNameBytes();

    /**
     * <code>.Profile.Sex sex = 2;</code>
     *
     * @return The enum numeric value on the wire for sex.
     */
    int getSexValue();

    /**
     * <code>.Profile.Sex sex = 2;</code>
     *
     * @return The sex.
     */
    com.feng.custom.info.Profile.Sex getSex();

    /**
     * <code>int32 age = 3;</code>
     *
     * @return The age.
     */
    int getAge();

    /**
     * <code>.google.protobuf.Any details = 4;</code>
     *
     * @return Whether the details field is set.
     */
    boolean hasDetails();

    /**
     * <code>.google.protobuf.Any details = 4;</code>
     *
     * @return The details.
     */
    com.google.protobuf.Any getDetails();

    /**
     * <code>.google.protobuf.Any details = 4;</code>
     */
    com.google.protobuf.AnyOrBuilder getDetailsOrBuilder();

    /**
     * <code>map&lt;string, string&gt; address = 5;</code>
     */
    int getAddressCount();

    /**
     * <code>map&lt;string, string&gt; address = 5;</code>
     */
    boolean containsAddress(
            java.lang.String key);

    /**
     * Use {@link #getAddressMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getAddress();

    /**
     * <code>map&lt;string, string&gt; address = 5;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getAddressMap();

    /**
     * <code>map&lt;string, string&gt; address = 5;</code>
     */

    java.lang.String getAddressOrDefault(
            java.lang.String key,
            java.lang.String defaultValue);

    /**
     * <code>map&lt;string, string&gt; address = 5;</code>
     */

    java.lang.String getAddressOrThrow(
            java.lang.String key);

    /**
     * <code>string father_no = 6;</code>
     *
     * @return The fatherNo.
     */
    java.lang.String getFatherNo();

    /**
     * <code>string father_no = 6;</code>
     *
     * @return The bytes for fatherNo.
     */
    com.google.protobuf.ByteString
    getFatherNoBytes();

    /**
     * <code>string mother_no = 7;</code>
     *
     * @return The motherNo.
     */
    java.lang.String getMotherNo();

    /**
     * <code>string mother_no = 7;</code>
     *
     * @return The bytes for motherNo.
     */
    com.google.protobuf.ByteString
    getMotherNoBytes();

    com.feng.custom.info.Profile.FamilyInfoCase getFamilyInfoCase();
}
