// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.feng.custom.info;

/**
 * <pre>
 * 个人信息
 * </pre>
 * <p>
 * Protobuf type {@code Profile}
 */
public final class Profile extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Profile)
        ProfileOrBuilder {
    public static final int NAME_FIELD_NUMBER = 1;
    public static final int SEX_FIELD_NUMBER = 2;
    public static final int AGE_FIELD_NUMBER = 3;
    public static final int DETAILS_FIELD_NUMBER = 4;
    public static final int ADDRESS_FIELD_NUMBER = 5;
    public static final int FATHER_NO_FIELD_NUMBER = 6;
    public static final int MOTHER_NO_FIELD_NUMBER = 7;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:Profile)
    private static final com.feng.custom.info.Profile DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<Profile>
            PARSER = new com.google.protobuf.AbstractParser<Profile>() {
        @java.lang.Override
        public Profile parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new Profile(input, extensionRegistry);
        }
    };

    static {
        DEFAULT_INSTANCE = new com.feng.custom.info.Profile();
    }

    private int familyInfoCase_ = 0;
    private java.lang.Object familyInfo_;

    private volatile java.lang.Object name_;
    private int sex_;
    private int age_;
    private com.google.protobuf.Any details_;
    private com.google.protobuf.MapField<
            java.lang.String, java.lang.String> address_;
    private byte memoizedIsInitialized = -1;
    // Use Profile.newBuilder() to construct.
    private Profile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private Profile() {
        name_ = "";
        sex_ = 0;
    }

    private Profile(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10: {
                        java.lang.String s = input.readStringRequireUtf8();

                        name_ = s;
                        break;
                    }
                    case 16: {
                        int rawValue = input.readEnum();

                        sex_ = rawValue;
                        break;
                    }
                    case 24: {

                        age_ = input.readInt32();
                        break;
                    }
                    case 34: {
                        com.google.protobuf.Any.Builder subBuilder = null;
                        if (details_ != null) {
                            subBuilder = details_.toBuilder();
                        }
                        details_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(details_);
                            details_ = subBuilder.buildPartial();
                        }

                        break;
                    }
                    case 42: {
                        if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                            address_ = com.google.protobuf.MapField.newMapField(
                                    AddressDefaultEntryHolder.defaultEntry);
                            mutable_bitField0_ |= 0x00000001;
                        }
                        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                                address__ = input.readMessage(
                                AddressDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                        address_.getMutableMap().put(
                                address__.getKey(), address__.getValue());
                        break;
                    }
                    case 50: {
                        java.lang.String s = input.readStringRequireUtf8();
                        familyInfoCase_ = 6;
                        familyInfo_ = s;
                        break;
                    }
                    case 58: {
                        java.lang.String s = input.readStringRequireUtf8();
                        familyInfoCase_ = 7;
                        familyInfo_ = s;
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    // Descriptor中包含字段和字段类型的描述
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.feng.custom.info.Person.internal_static_Profile_descriptor;
    }

    // 解析数据, 返回Profile
    public static com.feng.custom.info.Profile parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.feng.custom.info.Profile parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.feng.custom.info.Profile parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.feng.custom.info.Profile parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.feng.custom.info.Profile parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.feng.custom.info.Profile parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.feng.custom.info.Profile parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static com.feng.custom.info.Profile parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.feng.custom.info.Profile parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.feng.custom.info.Profile parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.feng.custom.info.Profile parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static com.feng.custom.info.Profile parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.feng.custom.info.Profile prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    // 得到Profile的实例
    public static com.feng.custom.info.Profile getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<Profile> parser() {
        return PARSER;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
        return new Profile();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
            int number) {
        switch (number) {
            case 5:
                return internalGetAddress();
            default:
                throw new RuntimeException(
                        "Invalid map field number: " + number);
        }
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.feng.custom.info.Person.internal_static_Profile_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.feng.custom.info.Profile.class, com.feng.custom.info.Profile.Builder.class);
    }

    public FamilyInfoCase
    getFamilyInfoCase() {
        return FamilyInfoCase.forNumber(
                familyInfoCase_);
    }

    /**
     * <code>string name = 1;</code>
     *
     * @return The name.
     */
    public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
        }
    }

    /**
     * <code>string name = 1;</code>
     *
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
    getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            name_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>.Profile.Sex sex = 2;</code>
     *
     * @return The enum numeric value on the wire for sex.
     */
    public int getSexValue() {
        return sex_;
    }

    /**
     * <code>.Profile.Sex sex = 2;</code>
     *
     * @return The sex.
     */
    public com.feng.custom.info.Profile.Sex getSex() {
        @SuppressWarnings("deprecation")
        com.feng.custom.info.Profile.Sex result = com.feng.custom.info.Profile.Sex.valueOf(sex_);
        return result == null ? com.feng.custom.info.Profile.Sex.UNRECOGNIZED : result;
    }

    /**
     * <code>int32 age = 3;</code>
     *
     * @return The age.
     */
    public int getAge() {
        return age_;
    }

    /**
     * <code>.google.protobuf.Any details = 4;</code>
     *
     * @return Whether the details field is set.
     */
    public boolean hasDetails() {
        return details_ != null;
    }

    /**
     * <code>.google.protobuf.Any details = 4;</code>
     *
     * @return The details.
     */
    public com.google.protobuf.Any getDetails() {
        return details_ == null ? com.google.protobuf.Any.getDefaultInstance() : details_;
    }

    /**
     * <code>.google.protobuf.Any details = 4;</code>
     */
    public com.google.protobuf.AnyOrBuilder getDetailsOrBuilder() {
        return getDetails();
    }

    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetAddress() {
        if (address_ == null) {
            return com.google.protobuf.MapField.emptyMapField(
                    AddressDefaultEntryHolder.defaultEntry);
        }
        return address_;
    }

    public int getAddressCount() {
        return internalGetAddress().getMap().size();
    }

    /**
     * <code>map&lt;string, string&gt; address = 5;</code>
     */

    public boolean containsAddress(
            java.lang.String key) {
        if (key == null) {
            throw new java.lang.NullPointerException();
        }
        return internalGetAddress().getMap().containsKey(key);
    }

    /**
     * Use {@link #getAddressMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getAddress() {
        return getAddressMap();
    }

    /**
     * <code>map&lt;string, string&gt; address = 5;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getAddressMap() {
        return internalGetAddress().getMap();
    }

    /**
     * <code>map&lt;string, string&gt; address = 5;</code>
     */

    public java.lang.String getAddressOrDefault(
            java.lang.String key,
            java.lang.String defaultValue) {
        if (key == null) {
            throw new java.lang.NullPointerException();
        }
        java.util.Map<java.lang.String, java.lang.String> map =
                internalGetAddress().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
    }

    /**
     * <code>map&lt;string, string&gt; address = 5;</code>
     */

    public java.lang.String getAddressOrThrow(
            java.lang.String key) {
        if (key == null) {
            throw new java.lang.NullPointerException();
        }
        java.util.Map<java.lang.String, java.lang.String> map =
                internalGetAddress().getMap();
        if (!map.containsKey(key)) {
            throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
    }

    /**
     * <code>string father_no = 6;</code>
     *
     * @return The fatherNo.
     */
    public java.lang.String getFatherNo() {
        java.lang.Object ref = "";
        if (familyInfoCase_ == 6) {
            ref = familyInfo_;
        }
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (familyInfoCase_ == 6) {
                familyInfo_ = s;
            }
            return s;
        }
    }

    /**
     * <code>string father_no = 6;</code>
     *
     * @return The bytes for fatherNo.
     */
    public com.google.protobuf.ByteString
    getFatherNoBytes() {
        java.lang.Object ref = "";
        if (familyInfoCase_ == 6) {
            ref = familyInfo_;
        }
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            if (familyInfoCase_ == 6) {
                familyInfo_ = b;
            }
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>string mother_no = 7;</code>
     *
     * @return The motherNo.
     */
    public java.lang.String getMotherNo() {
        java.lang.Object ref = "";
        if (familyInfoCase_ == 7) {
            ref = familyInfo_;
        }
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (familyInfoCase_ == 7) {
                familyInfo_ = s;
            }
            return s;
        }
    }

    /**
     * <code>string mother_no = 7;</code>
     *
     * @return The bytes for motherNo.
     */
    public com.google.protobuf.ByteString
    getMotherNoBytes() {
        java.lang.Object ref = "";
        if (familyInfoCase_ == 7) {
            ref = familyInfo_;
        }
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            if (familyInfoCase_ == 7) {
                familyInfo_ = b;
            }
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (!getNameBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
        }
        if (sex_ != com.feng.custom.info.Profile.Sex.BOY.getNumber()) {
            output.writeEnum(2, sex_);
        }
        if (age_ != 0) {
            output.writeInt32(3, age_);
        }
        if (details_ != null) {
            output.writeMessage(4, getDetails());
        }
        com.google.protobuf.GeneratedMessageV3
                .serializeStringMapTo(
                        output,
                        internalGetAddress(),
                        AddressDefaultEntryHolder.defaultEntry,
                        5);
        if (familyInfoCase_ == 6) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 6, familyInfo_);
        }
        if (familyInfoCase_ == 7) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 7, familyInfo_);
        }
        unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getNameBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
        }
        if (sex_ != com.feng.custom.info.Profile.Sex.BOY.getNumber()) {
            size += com.google.protobuf.CodedOutputStream
                    .computeEnumSize(2, sex_);
        }
        if (age_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(3, age_);
        }
        if (details_ != null) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(4, getDetails());
        }
        for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
                : internalGetAddress().getMap().entrySet()) {
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                    address__ = AddressDefaultEntryHolder.defaultEntry.newBuilderForType()
                    .setKey(entry.getKey())
                    .setValue(entry.getValue())
                    .build();
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(5, address__);
        }
        if (familyInfoCase_ == 6) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, familyInfo_);
        }
        if (familyInfoCase_ == 7) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, familyInfo_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.feng.custom.info.Profile)) {
            return super.equals(obj);
        }
        com.feng.custom.info.Profile other = (com.feng.custom.info.Profile) obj;

        if (!getName()
                .equals(other.getName())) return false;
        if (sex_ != other.sex_) return false;
        if (getAge()
                != other.getAge()) return false;
        if (hasDetails() != other.hasDetails()) return false;
        if (hasDetails()) {
            if (!getDetails()
                    .equals(other.getDetails())) return false;
        }
        if (!internalGetAddress().equals(
                other.internalGetAddress())) return false;
        if (!getFamilyInfoCase().equals(other.getFamilyInfoCase())) return false;
        switch (familyInfoCase_) {
            case 6:
                if (!getFatherNo()
                        .equals(other.getFatherNo())) return false;
                break;
            case 7:
                if (!getMotherNo()
                        .equals(other.getMotherNo())) return false;
                break;
            case 0:
            default:
        }
        return unknownFields.equals(other.unknownFields);
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (37 * hash) + SEX_FIELD_NUMBER;
        hash = (53 * hash) + sex_;
        hash = (37 * hash) + AGE_FIELD_NUMBER;
        hash = (53 * hash) + getAge();
        if (hasDetails()) {
            hash = (37 * hash) + DETAILS_FIELD_NUMBER;
            hash = (53 * hash) + getDetails().hashCode();
        }
        if (!internalGetAddress().getMap().isEmpty()) {
            hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
            hash = (53 * hash) + internalGetAddress().hashCode();
        }
        switch (familyInfoCase_) {
            case 6:
                hash = (37 * hash) + FATHER_NO_FIELD_NUMBER;
                hash = (53 * hash) + getFatherNo().hashCode();
                break;
            case 7:
                hash = (37 * hash) + MOTHER_NO_FIELD_NUMBER;
                hash = (53 * hash) + getMotherNo().hashCode();
                break;
            case 0:
            default:
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Profile> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public com.feng.custom.info.Profile getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * <pre>
     * 性别枚举
     * </pre>
     * <p>
     * Protobuf enum {@code Profile.Sex}
     */
    public enum Sex
            implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>BOY = 0;</code>
         */
        BOY(0),
        /**
         * <code>GIRL = 1;</code>
         */
        GIRL(1),

        // unknown的值
        UNRECOGNIZED(-1),
        ;

        /**
         * <code>BOY = 0;</code>
         */
        public static final int BOY_VALUE = 0;
        /**
         * <code>GIRL = 1;</code>
         */
        public static final int GIRL_VALUE = 1;
        private static final com.google.protobuf.Internal.EnumLiteMap<
                Sex> internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<Sex>() {
                    public Sex findValueByNumber(int number) {
                        return Sex.forNumber(number);
                    }
                };
        private static final Sex[] VALUES = values();
        private final int value;

        Sex(int value) {
            this.value = value;
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static Sex valueOf(int value) {
            return forNumber(value);
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         */
        public static Sex forNumber(int value) {
            switch (value) {
                case 0:
                    return BOY;
                case 1:
                    return GIRL;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<Sex>
        internalGetValueMap() {
            return internalValueMap;
        }

        public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
            return com.feng.custom.info.Profile.getDescriptor().getEnumTypes().get(0);
        }

        public static Sex valueOf(
                com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new java.lang.IllegalArgumentException(
                        "EnumValueDescriptor is not for this type.");
            }
            if (desc.getIndex() == -1) {
                return UNRECOGNIZED;
            }
            return VALUES[desc.getIndex()];
        }

        public final int getNumber() {
            if (this == UNRECOGNIZED) {
                throw new java.lang.IllegalArgumentException(
                        "Can't get the number of an unknown enum value.");
            }
            return value;
        }

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
            return getDescriptor().getValues().get(ordinal());
        }

        public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
            return getDescriptor();
        }

        // @@protoc_insertion_point(enum_scope:Profile.Sex)
    }

    public enum FamilyInfoCase
            implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
        FATHER_NO(6),
        MOTHER_NO(7),

        // 如果oneof未赋值
        FAMILYINFO_NOT_SET(0);
        private final int value;

        FamilyInfoCase(int value) {
            this.value = value;
        }

        /**
         * @param value The number of the enum to look for.
         * @return The enum associated with the given number.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static FamilyInfoCase valueOf(int value) {
            return forNumber(value);
        }

        public static FamilyInfoCase forNumber(int value) {
            switch (value) {
                case 6:
                    return FATHER_NO;
                case 7:
                    return MOTHER_NO;
                case 0:
                    return FAMILYINFO_NOT_SET;
                default:
                    return null;
            }
        }

        public int getNumber() {
            return this.value;
        }
    }

    private static final class AddressDefaultEntryHolder {
        static final com.google.protobuf.MapEntry<
                java.lang.String, java.lang.String> defaultEntry =
                com.google.protobuf.MapEntry
                        .newDefaultInstance(
                                com.feng.custom.info.Person.internal_static_Profile_AddressEntry_descriptor,
                                com.google.protobuf.WireFormat.FieldType.STRING,
                                "",
                                com.google.protobuf.WireFormat.FieldType.STRING,
                                "");
    }

    /**
     * <pre>
     * 个人信息
     * </pre>
     * <p>
     * Protobuf type {@code Profile}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:Profile)
            com.feng.custom.info.ProfileOrBuilder {
        private int familyInfoCase_ = 0;
        private java.lang.Object familyInfo_;
        private int bitField0_;
        private java.lang.Object name_ = "";
        private int sex_ = 0;
        private int age_;
        private com.google.protobuf.Any details_;
        private com.google.protobuf.SingleFieldBuilderV3<
                com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> detailsBuilder_;
        private com.google.protobuf.MapField<
                java.lang.String, java.lang.String> address_;

        // Construct using com.feng.custom.info.Profile.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.feng.custom.info.Person.internal_static_Profile_descriptor;
        }

        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMapField(
                int number) {
            switch (number) {
                case 5:
                    return internalGetAddress();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }

        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMutableMapField(
                int number) {
            switch (number) {
                case 5:
                    return internalGetMutableAddress();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.feng.custom.info.Person.internal_static_Profile_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.feng.custom.info.Profile.class, com.feng.custom.info.Profile.Builder.class);
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            name_ = "";

            sex_ = 0;

            age_ = 0;

            if (detailsBuilder_ == null) {
                details_ = null;
            } else {
                details_ = null;
                detailsBuilder_ = null;
            }
            internalGetMutableAddress().clear();
            familyInfoCase_ = 0;
            familyInfo_ = null;
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.feng.custom.info.Person.internal_static_Profile_descriptor;
        }

        @java.lang.Override
        public com.feng.custom.info.Profile getDefaultInstanceForType() {
            return com.feng.custom.info.Profile.getDefaultInstance();
        }

        @java.lang.Override
        public com.feng.custom.info.Profile build() {
            com.feng.custom.info.Profile result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public com.feng.custom.info.Profile buildPartial() {
            com.feng.custom.info.Profile result = new com.feng.custom.info.Profile(this);
            int from_bitField0_ = bitField0_;
            result.name_ = name_;
            result.sex_ = sex_;
            result.age_ = age_;
            if (detailsBuilder_ == null) {
                result.details_ = details_;
            } else {
                result.details_ = detailsBuilder_.build();
            }
            result.address_ = internalGetAddress();
            result.address_.makeImmutable();
            if (familyInfoCase_ == 6) {
                result.familyInfo_ = familyInfo_;
            }
            if (familyInfoCase_ == 7) {
                result.familyInfo_ = familyInfo_;
            }
            result.familyInfoCase_ = familyInfoCase_;
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.feng.custom.info.Profile) {
                return mergeFrom((com.feng.custom.info.Profile) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.feng.custom.info.Profile other) {
            if (other == com.feng.custom.info.Profile.getDefaultInstance()) return this;
            if (!other.getName().isEmpty()) {
                name_ = other.name_;
                onChanged();
            }
            if (other.sex_ != 0) {
                setSexValue(other.getSexValue());
            }
            if (other.getAge() != 0) {
                setAge(other.getAge());
            }
            if (other.hasDetails()) {
                mergeDetails(other.getDetails());
            }
            internalGetMutableAddress().mergeFrom(
                    other.internalGetAddress());
            switch (other.getFamilyInfoCase()) {
                case FATHER_NO: {
                    familyInfoCase_ = 6;
                    familyInfo_ = other.familyInfo_;
                    onChanged();
                    break;
                }
                case MOTHER_NO: {
                    familyInfoCase_ = 7;
                    familyInfo_ = other.familyInfo_;
                    onChanged();
                    break;
                }
                case FAMILYINFO_NOT_SET: {
                    break;
                }
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            com.feng.custom.info.Profile parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (com.feng.custom.info.Profile) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        public FamilyInfoCase
        getFamilyInfoCase() {
            return FamilyInfoCase.forNumber(
                    familyInfoCase_);
        }

        public Builder clearFamilyInfo() {
            familyInfoCase_ = 0;
            familyInfo_ = null;
            onChanged();
            return this;
        }

        /**
         * <code>string name = 1;</code>
         *
         * @return The name.
         */
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                name_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string name = 1;</code>
         *
         * @param value The name to set.
         * @return This builder for chaining.
         */
        public Builder setName(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            name_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string name = 1;</code>
         *
         * @return The bytes for name.
         */
        public com.google.protobuf.ByteString
        getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string name = 1;</code>
         *
         * @param value The bytes for name to set.
         * @return This builder for chaining.
         */
        public Builder setNameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            name_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string name = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearName() {

            name_ = getDefaultInstance().getName();
            onChanged();
            return this;
        }

        /**
         * <code>.Profile.Sex sex = 2;</code>
         *
         * @return The enum numeric value on the wire for sex.
         */
        public int getSexValue() {
            return sex_;
        }

        /**
         * <code>.Profile.Sex sex = 2;</code>
         *
         * @param value The enum numeric value on the wire for sex to set.
         * @return This builder for chaining.
         */
        public Builder setSexValue(int value) {
            sex_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>.Profile.Sex sex = 2;</code>
         *
         * @return The sex.
         */
        public com.feng.custom.info.Profile.Sex getSex() {
            @SuppressWarnings("deprecation")
            com.feng.custom.info.Profile.Sex result = com.feng.custom.info.Profile.Sex.valueOf(sex_);
            return result == null ? com.feng.custom.info.Profile.Sex.UNRECOGNIZED : result;
        }

        /**
         * <code>.Profile.Sex sex = 2;</code>
         *
         * @param value The sex to set.
         * @return This builder for chaining.
         */
        public Builder setSex(com.feng.custom.info.Profile.Sex value) {
            if (value == null) {
                throw new NullPointerException();
            }

            sex_ = value.getNumber();
            onChanged();
            return this;
        }

        /**
         * <code>.Profile.Sex sex = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearSex() {

            sex_ = 0;
            onChanged();
            return this;
        }

        /**
         * <code>int32 age = 3;</code>
         *
         * @return The age.
         */
        public int getAge() {
            return age_;
        }

        /**
         * <code>int32 age = 3;</code>
         *
         * @param value The age to set.
         * @return This builder for chaining.
         */
        public Builder setAge(int value) {

            age_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 age = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearAge() {

            age_ = 0;
            onChanged();
            return this;
        }

        /**
         * <code>.google.protobuf.Any details = 4;</code>
         *
         * @return Whether the details field is set.
         */
        public boolean hasDetails() {
            return detailsBuilder_ != null || details_ != null;
        }

        /**
         * <code>.google.protobuf.Any details = 4;</code>
         *
         * @return The details.
         */
        public com.google.protobuf.Any getDetails() {
            if (detailsBuilder_ == null) {
                return details_ == null ? com.google.protobuf.Any.getDefaultInstance() : details_;
            } else {
                return detailsBuilder_.getMessage();
            }
        }

        /**
         * <code>.google.protobuf.Any details = 4;</code>
         */
        public Builder setDetails(com.google.protobuf.Any value) {
            if (detailsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                details_ = value;
                onChanged();
            } else {
                detailsBuilder_.setMessage(value);
            }

            return this;
        }

        /**
         * <code>.google.protobuf.Any details = 4;</code>
         */
        public Builder setDetails(
                com.google.protobuf.Any.Builder builderForValue) {
            if (detailsBuilder_ == null) {
                details_ = builderForValue.build();
                onChanged();
            } else {
                detailsBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }

        /**
         * <code>.google.protobuf.Any details = 4;</code>
         */
        public Builder mergeDetails(com.google.protobuf.Any value) {
            if (detailsBuilder_ == null) {
                if (details_ != null) {
                    details_ =
                            com.google.protobuf.Any.newBuilder(details_).mergeFrom(value).buildPartial();
                } else {
                    details_ = value;
                }
                onChanged();
            } else {
                detailsBuilder_.mergeFrom(value);
            }

            return this;
        }

        /**
         * <code>.google.protobuf.Any details = 4;</code>
         */
        public Builder clearDetails() {
            if (detailsBuilder_ == null) {
                details_ = null;
                onChanged();
            } else {
                details_ = null;
                detailsBuilder_ = null;
            }

            return this;
        }

        /**
         * <code>.google.protobuf.Any details = 4;</code>
         */
        public com.google.protobuf.Any.Builder getDetailsBuilder() {

            onChanged();
            return getDetailsFieldBuilder().getBuilder();
        }

        /**
         * <code>.google.protobuf.Any details = 4;</code>
         */
        public com.google.protobuf.AnyOrBuilder getDetailsOrBuilder() {
            if (detailsBuilder_ != null) {
                return detailsBuilder_.getMessageOrBuilder();
            } else {
                return details_ == null ?
                        com.google.protobuf.Any.getDefaultInstance() : details_;
            }
        }

        /**
         * <code>.google.protobuf.Any details = 4;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>
        getDetailsFieldBuilder() {
            if (detailsBuilder_ == null) {
                detailsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                        getDetails(),
                        getParentForChildren(),
                        isClean());
                details_ = null;
            }
            return detailsBuilder_;
        }

        private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetAddress() {
            if (address_ == null) {
                return com.google.protobuf.MapField.emptyMapField(
                        AddressDefaultEntryHolder.defaultEntry);
            }
            return address_;
        }

        private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableAddress() {
            onChanged();
            if (address_ == null) {
                address_ = com.google.protobuf.MapField.newMapField(
                        AddressDefaultEntryHolder.defaultEntry);
            }
            if (!address_.isMutable()) {
                address_ = address_.copy();
            }
            return address_;
        }

        public int getAddressCount() {
            return internalGetAddress().getMap().size();
        }

        /**
         * <code>map&lt;string, string&gt; address = 5;</code>
         */

        public boolean containsAddress(
                java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            return internalGetAddress().getMap().containsKey(key);
        }

        /**
         * Use {@link #getAddressMap()} instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, java.lang.String> getAddress() {
            return getAddressMap();
        }

        /**
         * <code>map&lt;string, string&gt; address = 5;</code>
         */

        public java.util.Map<java.lang.String, java.lang.String> getAddressMap() {
            return internalGetAddress().getMap();
        }

        /**
         * <code>map&lt;string, string&gt; address = 5;</code>
         */

        public java.lang.String getAddressOrDefault(
                java.lang.String key,
                java.lang.String defaultValue) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String, java.lang.String> map =
                    internalGetAddress().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }

        /**
         * <code>map&lt;string, string&gt; address = 5;</code>
         */

        public java.lang.String getAddressOrThrow(
                java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String, java.lang.String> map =
                    internalGetAddress().getMap();
            if (!map.containsKey(key)) {
                throw new java.lang.IllegalArgumentException();
            }
            return map.get(key);
        }

        public Builder clearAddress() {
            internalGetMutableAddress().getMutableMap()
                    .clear();
            return this;
        }

        /**
         * <code>map&lt;string, string&gt; address = 5;</code>
         */

        public Builder removeAddress(
                java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            internalGetMutableAddress().getMutableMap()
                    .remove(key);
            return this;
        }

        /**
         * Use alternate mutation accessors instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, java.lang.String>
        getMutableAddress() {
            return internalGetMutableAddress().getMutableMap();
        }

        /**
         * <code>map&lt;string, string&gt; address = 5;</code>
         */
        public Builder putAddress(
                java.lang.String key,
                java.lang.String value) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            if (value == null) {
                throw new java.lang.NullPointerException();
            }
            internalGetMutableAddress().getMutableMap()
                    .put(key, value);
            return this;
        }

        /**
         * <code>map&lt;string, string&gt; address = 5;</code>
         */

        public Builder putAllAddress(
                java.util.Map<java.lang.String, java.lang.String> values) {
            internalGetMutableAddress().getMutableMap()
                    .putAll(values);
            return this;
        }

        /**
         * <code>string father_no = 6;</code>
         *
         * @return The fatherNo.
         */
        public java.lang.String getFatherNo() {
            java.lang.Object ref = "";
            if (familyInfoCase_ == 6) {
                ref = familyInfo_;
            }
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (familyInfoCase_ == 6) {
                    familyInfo_ = s;
                }
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string father_no = 6;</code>
         *
         * @param value The fatherNo to set.
         * @return This builder for chaining.
         */
        public Builder setFatherNo(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            familyInfoCase_ = 6;
            familyInfo_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string father_no = 6;</code>
         *
         * @return The bytes for fatherNo.
         */
        public com.google.protobuf.ByteString
        getFatherNoBytes() {
            java.lang.Object ref = "";
            if (familyInfoCase_ == 6) {
                ref = familyInfo_;
            }
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                if (familyInfoCase_ == 6) {
                    familyInfo_ = b;
                }
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string father_no = 6;</code>
         *
         * @param value The bytes for fatherNo to set.
         * @return This builder for chaining.
         */
        public Builder setFatherNoBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            familyInfoCase_ = 6;
            familyInfo_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string father_no = 6;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearFatherNo() {
            if (familyInfoCase_ == 6) {
                familyInfoCase_ = 0;
                familyInfo_ = null;
                onChanged();
            }
            return this;
        }

        /**
         * <code>string mother_no = 7;</code>
         *
         * @return The motherNo.
         */
        public java.lang.String getMotherNo() {
            java.lang.Object ref = "";
            if (familyInfoCase_ == 7) {
                ref = familyInfo_;
            }
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (familyInfoCase_ == 7) {
                    familyInfo_ = s;
                }
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string mother_no = 7;</code>
         *
         * @param value The motherNo to set.
         * @return This builder for chaining.
         */
        public Builder setMotherNo(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            familyInfoCase_ = 7;
            familyInfo_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string mother_no = 7;</code>
         *
         * @return The bytes for motherNo.
         */
        public com.google.protobuf.ByteString
        getMotherNoBytes() {
            java.lang.Object ref = "";
            if (familyInfoCase_ == 7) {
                ref = familyInfo_;
            }
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                if (familyInfoCase_ == 7) {
                    familyInfo_ = b;
                }
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string mother_no = 7;</code>
         *
         * @param value The bytes for motherNo to set.
         * @return This builder for chaining.
         */
        public Builder setMotherNoBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            familyInfoCase_ = 7;
            familyInfo_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string mother_no = 7;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearMotherNo() {
            if (familyInfoCase_ == 7) {
                familyInfoCase_ = 0;
                familyInfo_ = null;
                onChanged();
            }
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Profile)
    }

}

